version: '2'
services:
  web_app:
    container_name: flask_web_app
    image: flask_web_app:1.4
    build: .
    network_mode: bridge
    ports:
      - "8080:8080"
    links:
      - web_db:mysql
    depends_on:
      - web_db
    command: python3 app.py
    tty: true
  web_db:
    container_name: flask_web_db
    image: mysql:5.6
    network_mode: bridge
    environment:
      - MYSQL_DATABASE=FlaskWebApp
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=app
